"use client"

//import { Metadata } from "next";
import {
	useRouter,
} from 'next/navigation'

// export const metadata: Metadata = {
//   title: "pintogether",
//   description: "Generated by create next app",
//   icons: {
//     icon: [
//       {
//         url: "/logo/favicon.png",
//         media: "(prefers-color-scheme: light)",
//       },
//     ],
//   },
// };

export default function Page() {
  const router = useRouter();
  return(
    <div>
      <h1>Home</h1>
      가나다
      <button onClick={ () => router.push("/")}>버튼</button>
    </div>
  );
}
