import { Metadata } from "next";

export const metadata: Metadata = {
  title: "pintogether",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        url: "/logo/favicon.png",
        media: "(prefers-color-scheme: light)",
      },
    ],
  },
};

export default function Page() {

  return(
    <div>
      <h1>Home</h1>
      가나다
    </div>
  );
}
