import { Metadata } from "next";
import MainPage from "@/components/MainPage";

export const metadata: Metadata = {
	title: "pintogether",
	description: "Generated by create next app",
	icons: {
	  icon: [
		{
		  url: "/logo/favicon.png",
		  media: "(prefers-color-scheme: light)",
		},
	  ],
	},
  };

export default function Page() {
  return(
      <MainPage />
  );
}
